language: python
python:
- '3.7'
arch:
  - amd64
  - arm64
os: linux
env:
  global:
  - secure: qxCb/3A38lMTQUOkxVvkoBfuJSJgHStEupt5WC4rGVxzRqDYdAJVNppNFqR8BOemD22vXy0He0aZ0awAtAYZ4AbiRCknMekFzLauyBsNYDB48fJfaVnbRQQyFbCZdQJ2g6b0GBS+VRbMRLs25SjUwA8Y47TlX3wR3BpYNPR8IFHhAnJLClO1M7oCNBBtn6YK/tvVYMBJE1mlVXC4j8Yr18FBTvfiJF67yq8GttFeuYzvQopJzPbpP5eceH8HAU3zlirtB3iFRXOZMkPl8dWKf0BybV/DxXaw2DM5JdzjwM1XfiSeuFoTaKD+HdwanNPpKVS2d0kIBVMM7qrV3DaEbAIzX/dcIz1kNIQ2aE6EwpgpL29mXKinGpPT817qq5oJo4ixshDtOFWeGV6HBUq1prYs3mbcWFdBp2t3H4YyWCwt3TYlyWV9Bh1hvBzFp7qPYL734PEUbabUD89xCE7ZUzZhd3BfNFSR9t1sSKMbv5AKdNJEsnJy2zsz67RV/Vl9O+4vBeERXc3ykNkTcBnGyX24mDXsz/5Jm/zHES9UEUkTIoJOfqpMs4p6vnh1md4Rv0CYThUhAl0aF61TIen+epbxLJM3zB6jpvc2VQEdq4IoR0k+bHh5wUfb0OCmaLRVxlGr8e1yUG2OSwjyW03NSbh0dso7QJeHO/0wArecqdQ=
  - secure: Ipz5ABqvezu8TOgexYbpPxuxR3sdaevbjbc5DJR03uW93K2YbYSW2lDPDyfhsJ62bu+b6FqNjDFF2fapvLU30BLaGK8yTuCzn5TYmC0VHolSqVgkClHtC26ZP3fvOh+RZxs8y6+r9a5y5i2EFSi0olaQUabBSA8+l09TSSslJEJ5nbVErDkBCbtBcJgJW4k043JP4BH/Gi6gP1kiWV3gNXFDkXq5/owYQmEmaq5GvxH1bTihkblYUG9DSsU6S0F8OOovvDhdFmrKgNRvfzwoIakTc0PcryQABFb0xzVQhbebptIbO0UyCvr3SQvv9cvimajjKLLiUQSXDFGe2aCtq1VF0bPgSVmq6CMNAIeEogSbhQwWr0pYOMEa4qIySJpakkYJ9psJsOxcRDJz32QEltj3htoDXaWHl9bsjl+ut96Ei9FO6IL5C32oBQ5YdZnuI83j6ubXd4M+BNYHjOwPOYjoqtLxERpSI0neGfd957YHml00K9SdTwDBId8tq9cZMI5VkefQVZB6F51K6qVK0zMEhD6EMW9Q1h//rMk8mduU84sVaHEqVoxKN81NA0pg5WVhdqUR8JFHB1d+ysW0CmNI4AtgHFnesy/tiAO8aVXJhwsEblqg1grzVTtT48Bz0kn1qeiX9C+PNMfX/+cX31QoT9F9L3gcTpu1p4UUYUU=
services:
- docker
jobs:
  include:
    - stage: build
      script: docker build -t ${DOCKER_USERNAME}/lastfm-history:${TRAVIS_BRANCH} .

deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
